(function(){function ja(){l.style.display="block";H.style.display="block";I.innerHTML=q.value.length}function U(){l.style.display="none";H.style.display="none"}function ka(){l.style.display="block";J.style.display="block";x();K.innerHTML=r.value.length;L.innerHTML=r.value.length}function la(){l.style.display="none";J.style.display="none"}function ma(){var a=document.getElementById("fmt").value;3==a||5==a||V||(alert("This will save what you see in the textarea.\nChoose 'SVG Header' options to get a valid SVG file."),
V=!0);var a=new Blob([r.value],{type:"text/plain"}),b=document.createElement("a");b.download="svgedit.svg";b.innerHTML="Download File";window.webkitURL?b.href=window.webkitURL.createObjectURL(a):(b.href=window.URL.createObjectURL(a),b.onclick=function(a){document.body.removeChild(a.target)},b.style.display="none",document.body.appendChild(b));b.click()}function na(){l.style.display="block";M.style.display="block"}function N(){oa()?(l.style.display="none",M.style.display="none",g.round(m.value),f()):
alert("Enter valid viewBox\nviewBox = min-x min-y width height")}function pa(a){if(document.activeElement!==D){var b=+W.value;if(a.ctrlKey)return 37==a.keyCode&&(a.preventDefault(),u(-b,0)),39==a.keyCode&&(a.preventDefault(),u(b,0)),38==a.keyCode&&(a.preventDefault(),u(0,-b)),40==a.keyCode&&(a.preventDefault(),u(0,b)),!0;if(a.shiftKey){if(70==a.keyCode)return a.preventDefault(),(X=!X)?(h.setAttribute("fill","black"),h.setAttribute("stroke-width",0)):(h.setAttribute("fill","none"),h.setAttribute("stroke-width",
3)),f(),!0;if(67==a.keyCode)return a.preventDefault(),Y(),!0;if(78==a.keyCode)return a.preventDefault(),O=!O,f(),!0;if(83==a.keyCode)return a.preventDefault(),B=(B+1)%4,f(),!0;if(90==a.keyCode)return a.preventDefault(),g.scale(.9),f(),!0;if(88==a.keyCode)return a.preventDefault(),g.scale(1.1),f(),!0;if(81==a.keyCode)return a.preventDefault(),g.scale(.99),f(),!0;if(87==a.keyCode)return a.preventDefault(),g.scale(1.01),f(),!0;37==a.keyCode&&(a.preventDefault(),y(3));39==a.keyCode&&(a.preventDefault(),
y(1));38==a.keyCode&&(a.preventDefault(),y(0));40==a.keyCode&&(a.preventDefault(),y(2));107==a.keyCode&&(a.preventDefault(),Z(0));109==a.keyCode&&(a.preventDefault(),Z(2))}return!0}}function qa(a){a.preventDefault();if(z){var b=a.movementX,d=a.movementY,b=b*aa,d=d*ba;u(b,d)}E.x=a.clientX;E.y=a.clientY;a=svg.getScreenCTM();a.e=Math.floor(a.e);a.a=Math.floor(a.a);a=E.matrixTransform(a.inverse());P.innerHTML="("+Math.round(1E3*a.x)/1E3+", "+Math.round(1E3*a.y)/1E3+")";return!0}function ra(){z=!1;P.innerHTML=
"";return!0}function sa(a){a.preventDefault();return z=!0}function ta(){z=!1;return!0}function ca(a){window.clearTimeout(da);Q.innerHTML=a;da=setTimeout(ua,2E3)}function ua(){Q.innerHTML=""}function va(){var a=this.value;n.value="0 0 "+a+" "+a}function x(){var a=document.getElementById("brk").value,b=document.getElementById("fmt").value,d=document.getElementById("att").value,f=n.value,c=g["export"](),e=[];if(0==a)e=[c];else for(var a=1==a?/([Mm].*?[Zz])/g:/([Mm].*?[Zz])[Zz]/g,h;(h=a.exec(c))&&void 0!=
h[1];)e.push(h[1]);if(0==b)r.value=e.join("\n");else if(1==b){for(c=0;c<e.length;c++)e[c]='"'+e[c]+'"';r.value="var svg = ["+e.join()+"]"}else{for(c=0;c<e.length;c++)e[c]=1==d||2==d?'<path class="p'+(c+1)+'" d="'+e[c]+'"/>':'<path d="'+e[c]+'"/>';c=e.join("\n");if(4==b||5==b)c=0==d?"<symbol>\n"+c+"\n</symbol>":1==d?'<symbol id="_">\n'+c+"\n</symbol>":2==d?'<symbol id="_" viewBox="'+f+'">\n'+c+"\n</symbol>":'<symbol viewBox="'+f+'">\n'+c+"\n</symbol>";if(3==b||5==b)c='<svg ns="http://www.w3.org/2000/svg" viewBox="'+
f+'">\n'+c+"\n</svg>";r.value=c}}function oa(){var a=n.value,a=a.trim(),a=a.split(" ");if(4!=a.length)return!1;var b=+a[0],f=+a[1],g=+a[2],a=+a[3];if(isNaN(b)||isNaN(f)||isNaN(g)||isNaN(a)||1>d[2]||1>d[3])return!1;d[0]=b;d[1]=f;d[2]=g;d[3]=a;R();return!0}function R(){var a=d[0]+" "+d[1]+" "+d[2]+" "+d[3];n.value=a;t.setAttribute("viewBox",a);v=d[0]+d[2]/2;w=d[1]+d[3]/2;aa=d[2]/512;ba=d[3]/512;F=d[2]/512;S=3*F;T=6*F;ca(a)}function wa(){I.innerHTML=q.value.length}function ea(){m.value=3;g.round(m.value);
g["import"](q.value);f();U();fa.innerHTML=q.value.length}function xa(){var a=Number(ga.value),b=Number(ha.value);!isNaN(a)&&a&&!isNaN(b)&&b&&(g.scale(a/b),f(),N())}function ya(){g.absolute();f()}function za(){g.relative();f()}function Aa(){m.value=0;g.round(m.value);f()}function Ba(){g.flip(v,void 0);f()}function Ca(){g.flip(void 0,w);f()}function Da(){g.rotate(v,w,5);f()}function Ea(){g.rotate(v,w,-5);f()}function Y(){g.center(v,w);f();N()}function u(a,b){g.move(a,b);f()}function y(a){var b=d[2]/
10;0==a&&(d[1]-=b);2==a&&(d[1]+=b);3==a&&(d[0]-=b);1==a&&(d[0]+=b);R();f()}function Z(a){var b=d[2]/10;0==a&&(d[2]-=b,d[3]-=b);2==a&&(d[2]+=b,d[3]+=b);R();f()}function Fa(){g.analyse(ia.value);f()}function Ga(){for(var a="",b=D.value.split("\n"),d=0;d<b.length;d++){var h=b[d],c=h.indexOf("\t");0<=c&&(h=h.substr(c+1));c=h.indexOf("#");a=0>c?a+(h+" "):a+(h.substring(0,c)+" ")}g["import"](a);f()}function G(a,b,d,f,c){var e=document.createElementNS("http://www.w3.org/2000/svg","rect");e.setAttribute("id",
"r"+d);e.setAttribute("class","m"+f);e.setAttribute("x",a-S);e.setAttribute("y",b-S);e.setAttribute("width",T);e.setAttribute("height",T);e.setAttribute("fill",c);e.setAttribute("stroke","white");e.setAttribute("stroke-width",F);e.onmousemove=Ha;C.appendChild(e)}function Ha(){var a=this.getAttribute("id").substr(1),b=this.getAttribute("class").substr(1);"0"!=b&&(a+=" - "+b);ca(a)}function f(){for(var a=g.exportlist();C.firstChild;)C.removeChild(C.firstChild);for(var b="",d=0,f=0,c=0;c<a.length;c++){var e=
a[c].t,l=a[c].x,m=a[c].y,q=a[c].px,u=a[c].py,k=a[c].x1,p=a[c].y1,n=a[c].x2,t=a[c].y2,v=a[c].r1,w=a[c].r2,x=a[c].ar,y=a[c].af,z=a[c].sf,A=a[c].info;O&&(b+=c+1+"\t");b+=e;b+=void 0==k?"":" "+k;b+=void 0==p?"":" "+p;b+=void 0==n?"":" "+n;b+=void 0==t?"":" "+t;b+=void 0==v?"":" "+v;b+=void 0==w?"":" "+w;b+=void 0==x?"":" "+x;b+=void 0==y?"":y?" 1":" 0";b+=void 0==z?"":z?" 1":" 0";b+="V"==e.toUpperCase()||"Z"==e.toUpperCase()?"":" "+l;b+="H"==e.toUpperCase()||"Z"==e.toUpperCase()?"":" "+m;A=""!=A?" # "+
A:"";A="M"==e.toUpperCase()?A+" # "+ ++f:A;b+=A;b+="\n";!B||3==B&&"M"!=e.toUpperCase()||"Z"==e.toUpperCase()||(2==B&&(void 0!=k&&(k=96>e.charCodeAt(0)?k:k+q,p=96>e.charCodeAt(0)?p:p+u,G(k,p,c+1,0,"blue")),void 0!=n&&(k=96>e.charCodeAt(0)?n:n+q,p=96>e.charCodeAt(0)?t:t+u,G(k,p,c+1,0,"blue"))),k=96>e.charCodeAt(0)?l:l+q,p=96>e.charCodeAt(0)?m:m+u,"M"==e.toUpperCase()?G(k,p,c+1,++d,"red"):G(k,p,c+1,0,"red"))}D.value=b;h.setAttribute("d",g["export"]());r.value=g["export"]();K.innerHTML=r.value.length;
L.innerHTML=r.value.length}var l,H,J,M,q,r,I,K,fa,L,P,Q,n,ha,ga,W,m,ia,t,h,D,C,g,da,z,E,d=[0,0,512,512],v=256,w=256,aa=1,ba=1,F=1,S=3,T=6,B=1,X=!0,O=!1,V=!1;window.onload=function(){document.getElementById("btnimport").onclick=ja;document.getElementById("btnexport").onclick=ka;document.getElementById("btndownload").onclick=ma;document.getElementById("btndoimport").onclick=ea;document.getElementById("btnoptions").onclick=na;document.getElementById("btnabsolute").onclick=ya;document.getElementById("btnrelative").onclick=
za;document.getElementById("btninteger").onclick=Aa;document.getElementById("btnflipver").onclick=Ba;document.getElementById("btnfliphor").onclick=Ca;document.getElementById("btnrotatecw").onclick=Da;document.getElementById("btnrotatecc").onclick=Ea;document.getElementById("btncenter").onclick=Y;document.getElementById("btnscale").onclick=xa;document.getElementById("btnanalyse").onclick=Fa;document.getElementById("btnimportlist").onclick=Ga;document.getElementById("btncloseimport").onclick=U;document.getElementById("btncloseexport").onclick=
la;document.getElementById("btncloseoptions").onclick=N;document.getElementById("brk").onchange=x;document.getElementById("fmt").onchange=x;document.getElementById("att").onchange=x;document.getElementById("setviewbox").onchange=va;l=document.getElementById("overlay");H=document.getElementById("divimport");J=document.getElementById("divexport");M=document.getElementById("divoptions");q=document.getElementById("input");r=document.getElementById("output");I=document.getElementById("isize1");K=document.getElementById("osize1");
fa=document.getElementById("isize2");L=document.getElementById("osize2");P=document.getElementById("coors");Q=document.getElementById("info");n=document.getElementById("viewbox");ha=document.getElementById("unitfr");ga=document.getElementById("unitto");W=document.getElementById("movefactor");m=document.getElementById("rounddigit");ia=document.getElementById("adistance");D=document.getElementById("list");t=document.getElementById("svg");h=document.getElementById("path");C=document.getElementById("g");
q.onkeyup=wa;t.onmousemove=qa;t.onmouseout=ra;h.onmousedown=sa;h.onmouseup=ta;window.onkeydown=pa;h.setAttribute("stroke","black");E=t.createSVGPoint();g=new SVGPath;g.round(m.value);ea()}})();
